# Generated by Django 3.1.4 on 2020-12-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_description',
            field=models.CharField(blank=True, help_text='this is the short description that will appear in the project card on both the main slider and other work card deck.', max_length=75, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description',
            field=models.CharField(blank=True, help_text='this is the longer description that will show up beneath the slider on the project detail page.', max_length=75, verbose_name='full description'),
        ),
    ]
