# Generated by Django 3.1.4 on 2020-12-11 23:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201211_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_credits',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='these are the credits that will show up beneath the slider on the project detail page. please put credits in list format.', max_length=250, verbose_name='project credits'),
        ),
    ]
