# Generated by Django 3.1.4 on 2020-12-11 23:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_project_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media_gallery',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('video', wagtail.core.blocks.CharBlock(help_text='paste video url here', required=True))], blank=True, null=True),
        ),
    ]
