# Generated by Django 3.1.4 on 2020-12-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.CharField(blank=True, help_text='this is the longer description that will show up beneath the slider on the project detail page.', max_length=250, verbose_name='full description'),
        ),
    ]
