# Generated by Django 3.1.4 on 2020-12-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='bio',
            field=models.TextField(blank=True, max_length=750, verbose_name='bio'),
        ),
    ]
